.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. microcurrency_qt test_microcurrency_qt
clean: FORCE
	$(MAKE) -C .. microcurrency_qt_clean test_microcurrency_qt_clean
check: FORCE
	$(MAKE) -C .. test_microcurrency_qt_check
microcurrency-qt microcurrency-qt.exe: FORCE
	 $(MAKE) -C .. microcurrency_qt
apk: FORCE
	$(MAKE) -C .. microcurrency_qt_apk
